# This file is used by Acquia Pipelines continuous integration. It builds
# Demo Framework and runs its functional tests. Upon success, an artifact is
# deployed to the demoframeworktests (adef0efb-9742-4158-9a17-3554db4c5e7c) sub
# on Acquia cloud.
version: 1.1.0
services:
  - mysql
  - php:
    version: 7.1

variables:
  global:
    SCENARIO: none

events:
  build:
    steps:
      - setup:
          type: script
          script:
            # Add Composer's local bin directory to the PATH so that we will be
            # running our installed versions of Drush, PHPCS, Behat, etc.
            - export PATH="$HOME/.composer/vendor/bin:$SOURCE_DIR/bin:$PATH"
            - composer validate --no-check-all --ansi --no-interaction
            - composer install
      - install:
          type: script
          script:
            - cd $SOURCE_DIR
            - mysql -u root -proot -e 'CREATE DATABASE drupal;'
            - phing install -Ddb.password=root -Ddb.database=drupal -Durl=http://127.0.0.1:8080
            - if [[ "$SCENARIO" != none ]]; then cd docroot; ../bin/drush cache-rebuild; ../bin/drush es $SCENARIO; cd ..; fi
      - test:
          type: script
          script:
            - cd $SOURCE_DIR/docroot
            - drush runserver --default-server=builtin 8080 &>/dev/null &
            - phantomjs --webdriver=4444 > /dev/null &
            - sleep 10
            - behat --stop-on-failure --config ./sites/default/files/behat.yml --tags="df&&~javascript"
            - if [[ "$SCENARIO" != none ]]; then behat --stop-on-failure --config ./sites/default/files/behat.yml --tags="$SCENARIO&&~javascript"; fi
      - cleanup:
          type: script
          script:
            # Remove drush so our version doesn't interfere with cloud commands.
            - composer remove drush/drush --dev
            # Setup settings file and codebase with minimum required for cloud.
            - cd $SOURCE_DIR
            - phing cloud-settings
