dependencies:
  module:
    - crop
effects:
  c1815ac9-f69d-48f8-a301-fe87de0c3dd8:
    uuid: c1815ac9-f69d-48f8-a301-fe87de0c3dd8
    id: image_scale_and_crop
    weight: 2
    data:
      width: 100
      height: 100
  65fa2c01-c68c-4802-b689-a3d40b74f621:
    uuid: 65fa2c01-c68c-4802-b689-a3d40b74f621
    id: crop_crop
    weight: 2
    data:
      crop_type: square

