dependencies:
  module:
    - crop
effects:
  bddf0d06-42f9-4c75-a700-a33cafa25ea0:
    uuid: bddf0d06-42f9-4c75-a700-a33cafa25ea0
    id: image_scale
    weight: -9
    data:
      width: 350
      height: 350
      upscale: false
  94c3cb9c-7d93-4006-b3ad-176ad17bbc47:
    uuid: 94c3cb9c-7d93-4006-b3ad-176ad17bbc47
    id: crop_crop
    weight: -10
    data:
      crop_type: square

