dependencies:
  module:
    - crop
effects:
  f877f421-62b5-4d01-9500-b5b0003263a4:
    uuid: f877f421-62b5-4d01-9500-b5b0003263a4
    id: image_scale_and_crop
    weight: -9
    data:
      width: 345
      height: 345
  ba3ecbd4-5b23-459c-b91e-5b080a7dca23:
    uuid: ba3ecbd4-5b23-459c-b91e-5b080a7dca23
    id: crop_crop
    weight: -10
    data:
      crop_type: square

